org: jsoareez
service: async-report

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  architecture: arm64
  memorySize: 128
  environment:
    DYNAMO_LEADS_TABLE: !Ref LeadsTable
    GENERATE_REPORT_QUEUE_URL: !Ref GenerateReportQueue
  iam:
    role:
      statements:
        # DynamoDB
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: !GetAtt LeadsTable.Arn
        # SQS
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: !GetAtt GenerateReportQueue.Arn

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  # HTTP
  populateDynamo:
    handler: src/functions/http/populateDynamo.handler
    timeout: 25
    memorySize: 1024
    events:
      - httpApi:
          path: /populate-dynamo
          method: POST
  generateReport:
    handler: src/functions/http/generateReport.handler
    events:
      - httpApi:
          path: /generate-report
          method: POST
  # QUEUE
  processReport:
    handler: src/functions/queues/processReport.handler
    events:
      - sqs:
          arn: !GetAtt GenerateReportQueue.Arn
          batchSize: 1

resources:
  # DynamoDB
  - ${file(./resources/dynamodb/LeadsTable.yml)}
  # SQS
  - ${file(./resources/sqs/GenerateReportQueue.yml)}
  # S3
  - ${file(./resources/s3/ReportsBucket.yml)}
